#!/usr/bin/env bash
# Flip local vs Cloud SQL vs AlloyDB demo flags (same codebase — env only).
# Usage:
#   ./scripts/switch_backend.sh local     # USE_ALLOYDB=false DEMO_SEED=true
#   ./scripts/switch_backend.sh cloudsql  # USE_ALLOYDB=false DEMO_SEED=false (GCP Cloud SQL)
#   ./scripts/switch_backend.sh alloydb   # USE_ALLOYDB=true  DEMO_SEED=false
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:?mode: local|cloudsql|alloydb}"
TARGET="${ROOT}/configs/backend.switch.env"

case "$MODE" in
  local)
    cat >"$TARGET" <<'EOF'
# Generated by scripts/switch_backend.sh — do not commit secrets here.
# Sourced after configs/{local|prod}.env via: set -a; source configs/backend.switch.env; set +a
USE_ALLOYDB=false
DEMO_SEED=true
APP_ENV=local
EOF
    echo "Backend → local Postgres (USE_ALLOYDB=false DEMO_SEED=true)"
    echo "  DATABASE_URL stays in configs/local.env / .env"
    ;;
  cloudsql)
    cat >"$TARGET" <<'EOF'
# Generated by scripts/switch_backend.sh — do not commit secrets here.
USE_ALLOYDB=false
DEMO_SEED=false
APP_ENV=prod
# Set CLOUD_SQL_INSTANCE and inject DATABASE_URL from Secret Manager at deploy.
# CLOUD_SQL_INSTANCE=project-ca974159-bdd0-4647-b53:us-central1:checkpoint-pg
EOF
    echo "Backend → Cloud SQL (USE_ALLOYDB=false DEMO_SEED=false)"
    echo "  Export DATABASE_URL from Secret Manager or Cloud Run secrets."
    ;;
  alloydb)
    cat >"$TARGET" <<'EOF'
# Generated by scripts/switch_backend.sh — do not commit secrets here.
USE_ALLOYDB=true
DEMO_SEED=false
APP_ENV=prod
# Start AlloyDB Auth Proxy, then:
# export DATABASE_URL=postgresql+psycopg://checkpoint:SECRET@127.0.0.1:5433/aggregation
# ALLOYDB_CLUSTER=...
# ALLOYDB_INSTANCE=...
EOF
    echo "Backend → AlloyDB (USE_ALLOYDB=true DEMO_SEED=false)"
    echo "  Start Auth Proxy and export DATABASE_URL (see deploy/gcp/README.md)."
    ;;
  *)
    echo "Usage: $0 local|cloudsql|alloydb" >&2
    exit 1
    ;;
esac
echo "Wrote $TARGET"
echo "Apply:  set -a && source configs/backend.switch.env && set +a"
