from __future__ import annotations

from typing import Any, Optional, Protocol, runtime_checkable


@runtime_checkable
class EventPublisher(Protocol):
    def publish_checkpoint(self, event: dict | object) -> None: ...

    def publish_retry(self, event: dict, key: str) -> None: ...

    def publish_dlq(self, dlq_payload: dict, key: str = "dlq") -> None: ...

    def publish_aggregation(self, event: dict, key: str) -> None: ...

    def flush(self, timeout: float = 10.0) -> int: ...


@runtime_checkable
class AggregateCachePort(Protocol):
    def get(self, date: str, counter_id: str, meal_type: str) -> Optional[dict]: ...

    def set(self, date: str, counter_id: str, meal_type: str, payload: dict) -> None: ...

    def invalidate(self, date: str, counter_id: str, meal_type: str) -> None: ...

    def get_cafe(self, date: str, cafe_id: str) -> Optional[dict[str, Any]]: ...

    def set_cafe(self, date: str, cafe_id: str, payload: dict) -> None: ...


@runtime_checkable
class UnitOfWork(Protocol):
    def commit(self) -> None: ...

    def rollback(self) -> None: ...
